- name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ env.REPO }}:latest
            docker stop aggregator || true
            docker rm aggregator || true
            docker run -d \
              -p 3000:3000 \
              --env-file /root/go-api-aggregator/.env \
              --name aggregator \
              --restart unless-stopped \
              ghcr.io/${{ env.REPO }}:latest
            sleep 3
            docker ps | grep aggregator || echo "WARNING: Container not running!"
            docker image prune -f